spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    # false 不向注册中心注册自己
    register-with-eureka: false
    # false 不需要向注册中心获取实例
    fetch-registry: false

  server:
    # 获取不到实例等待时间
    wait-time-in-ms-when-sync-empty: 0
